version: '3'
services:

    # Database
    mariadb:
        build:
            context: ./
            dockerfile: app.dockerfile
        container_name: 'mariadb'
        expose:
            - "3306"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
        restart: on-failure
        volumes:
            - ${DATA_DIR:-./data}:/var/lib/mysql